### ISSUE TITLE
Keys modified by OneShot do not repeat

### ISSUE THREAD

**Issue by cdisselkoen** [keyboardio/Kaleidoscope-OneShot#11]
This might have the same underlying cause as #10, but I'll report it separately.

Steps to reproduce:
1. Start with the 'example' sketch from this repo, but change the `Key_LeftShift` to `OSM(LeftShift)`.  I've reproduced this on the most recent version of this plugin (at time of writing), `2fe4ef3`.
2. Hold the right shift (which is not a OneShot in this sketch) and a letter key together.  As expected, the shifted letter key is repeatedly input until you release it.
3. Tap the left shift (which is a OneShot), then hold the letter key.  The key does not repeat.
4. The same problematic behavior is observed if you hold the left shift and the letter key - the key does not repeat.

I'll see if I can find the root cause of this myself, but I decided to formally report it first.

**Comment by algernon** [comment]
The root cause is the masking, which was used to fix #4. I suppose we should do that a bit more... intelligently, and resume repeating if the key is held longer than some time.

I don't think this has anything to do with #10.

**Comment by algernon** [comment]
As discussed in #4, the fix here is to not do any masking when one-shot modifiers are used, only for the one-shot layer case.
