### ISSUE TITLE
generate keydown events while oneshot effect is active

### ISSUE THREAD

**Issue by ToyKeeper** [keyboardio/Kaleidoscope-OneShot#13]
If it's not difficult to do, it might be nice to generate artificial keydown events for oneshotted keys while they are active.  This would allow other plugins to react to the key's logical "down" state as if the user was still holding it.

These events would be handled by functions like this:

```C
Key MyPlugin::eventHandlerHook(Key mapped_key, byte row, byte col, uint8_t key_state) {
  if (keyIsPressed(key_state)) {
    do_something();
  }
  return mapped_key;
}
```

In my case specifically, I'd use this to make the wavepool react as if the key still had a finger on it.  This is partly because it looks neat, and partly because it could eliminate the need for the ActiveModColorEffect plugin when the active lighting mode handles the events.

**Comment by algernon** [comment]
I'm not sure I understand the scenario... To be clear, all key activation `OneShot` does goes through `handleKeyswitchEvent`, so other plugins should be able to intercept those events too, as long as there are no plugins in front of them that swallow said events. Order matters in this case.

One thing though... we call `loopHook` twice in a single scan cycle: once just after scanning the matrix (but before sending and then clearing the report), and once more after sending the report. LED modes update during the first call, after the event loop hooks have ran.

I'm not quite sure why OneShot stuff do not reach Wavepool yet - will run a few experiments later today to learn something. But figure I'll post a brief explanation of how the various hooks run.

**Comment by gedankenexperimenter** [comment]
Having recently looked through the OneShot code for other reasons, I think I can explain what @Toykeeper wants that is currently missing. When OneShot calls `handleKeyswitchEvent()` to inject a OneShot keycode, it uses `UNKNOWN_KEYSWITCH_LOCATION`, but Wavepool wants to know the row & column values of pressed keys.

**Comment by algernon** [comment]
Aha! THAT I can fix with reasonable ease. Thank you!

**Comment by gedankenexperimenter** [comment]
Oops. I should have elaborated. Adding this feature is going to make OneShot incompatible with Qukeys.

**Comment by gedankenexperimenter** [comment]
It occurs to me that I can add an additional check to Qukeys to compensate, though. It already ignores all events with out-of-bounds `row` or `col` values; I can also have it ignore key states with the `INJECTED` flag.
