### ISSUE TITLE
Do OneShot modifiers survive layer changes?

### ISSUE THREAD

**Issue by gedankenexperimenter** [keyboardio/Kaleidoscope-OneShot#14]
If I set a `OneShot` (or sticky) modifier, then change layers, will that modifier still be "pressed"? I was considering the possibility of configuring `alt` on a left thumb key, and `gui` on a right thumb key, and swapping them on a different layer, so typing `fn`+`gui` would get me `alt` (which otherwise might not be accessible on the right hand), but I would then want to type a key (or keys) on the base layer that are overwritten on the `fn` layer. I'm suggesting this in case this usage hasn't been considered yet.

**Comment by algernon** [comment]
I'm not a hundred percent sure I understand the scenario, but: one-shot keys (modifiers and layer keys too) are *not* cancelled when pressing any other one-shot key. So if you press a one-shot modifier, then a one-shot layer key, then the modifier will remain active. If you press a one-shot modifier, and a normal layer key, that will cancel the one-shot modifier.

If a key is `OSM(LeftGUI)` on one layer, and `OSM(LeftAlt)` on another, whether you get `GUI` or `Alt` out of it depends on which layer was active when you pressed the key.

Does this answer you question?

**Comment by gedankenexperimenter** [comment]
Maybe.

I'm only asking about a single `OneShot` modifier key being used. The layer change in my example would be a temporary one in effect while the `fn` key was held down.

**Comment by algernon** [comment]
If the `Fn` key is a one-shot layer key, then a one-shot modifier pressed before `Fn` would survive through the layer change, yes.

**Comment by gedankenexperimenter** [comment]
> If the Fn key is a one-shot layer key, then a one-shot modifier pressed before Fn would survive through the layer change, yes.

And if it's not a one-shot layer (which it wasn't, in my example)?

**Comment by algernon** [comment]
In that case, the `Fn` will consume the one-shot modifier at the moment. This can be changed, with reasonable ease.

**Comment by glasser** [comment]
Can you give advice on making that reasonably easy change?

I'm trying out making all my thumb keys be one shot but keeping the fn layer switch normal. Weirdly, if LED-ActiveModColor is not lying to me, hitting fn eats any active oneshot ctrl shift or gui, but not alt. I would like that to not happen so i can lock some modifiers and then hit arrow keys on my fn layer.

**Comment by algernon** [comment]
[This](https://github.com/keyboardio/Kaleidoscope-OneShot/blob/b96067b2b63234be291695c7c20548c1a5575e24/src/Kaleidoscope/OneShot.cpp#L154-L159) is the place where you need to make changes. Before this block of code, if you add a branch that checks if `mapped_key` is a layer key, and lets it through without cancelling OneShot, that should do the trick.

This new branch shoud call `saveAsPrevious()` though, but not anything else the linked one does.

**Comment by glasser** [comment]
Should this be a preference or always happen?

**Comment by algernon** [comment]
Not sure. I *think* I'd prefer a preference, but that's just a hunch.

**Comment by algernon** [comment]
I just run into a case where I need `OneShot` to survive a layer change, so I'll see about getting this implemented.

**Comment by glasser** [comment]
Thanks, I've been pretty overwhelmed.

**Comment by algernon** [comment]
Took a fair bit longer to get around to doing this, sorry about that!

**Comment by glasser** [comment]
Thanks, I guess I've had less time for keyboard hacking than I thought!
