### ISSUE TITLE
Document how to tap for one shot effect vs. standard keypress

### ISSUE THREAD

**Issue by benshine** [keyboardio/Kaleidoscope-OneShot#24]
I think I've finally figured this out: quick taps invoke one-shot mode, and slightly longer keypresses are just normal; they do not enter one-shot mode.

If that's right, I can do a PR adding this to the README.

**Comment by algernon** [comment]
This is briefly documented [here](https://github.com/keyboardio/Kaleidoscope-OneShot#hold_time_out) - though that's not the most visible place. If you can add something like it to elsewhere in the README, to a more prominent place (the intro sounds like a good place for it), I'd love to merge that PR.
