### ISSUE TITLE
OneShot should support more keys

### ISSUE THREAD

**Issue by MaxG87** [keyboardio/Kaleidoscope-OneShot#32]
I tried to set up OneShot today and it worked quite well. I tried to use that for Key_CapsLock as this is a very important modifier key in the Neo2 layout I use. Neo2 has even more modifier keys on normal keys like Pipe, but I am not sure about there key codes now.

Unfortunately, OneShot seems to not support CapsLock. Using OSM(CapsLock) results in a disabled key. I read the OSM define but did not find the reason for that behaviour.

Thus, please support more keys. At least it would be great to know the reason, so I could implement my own workaround.

Thank you very much.

**Comment by algernon** [comment]
There are a number of reasons `OneShot` doesn't support anything else but modifiers and layers: we need to store information about each possible one-shot key, limiting that to 8 modifiers + 8 one-shot layers allows us to fit everything we need into 16 bits per group of info. If I add any more, I'd need to increase that to 24 bits at least, which would increase PROGMEM use by about 100 bytes at a minimum.

On top of that, supporting other keys would increase the number of different one-shot variants: along modifiers and layers, we'd now have normal keys too, which would further complicate the code.

I'm afraid that at this time, I do not feel comfortable with supporting more keys.

**Comment by MaxG87** [comment]
Thank you for the explanation. I understand that these restrictions make it harder to support new keys.

However, I think it would be helpful and achievable to add compile time checks, preventing compilation in case someone uses a non modifier key. I think that this could be achieved with the use of `static_assert'.

A further, new item on a wishlist would be to allow a tradeof between layers and keys to be configurable. E.g. I use only 2 layers, because Neo2 has layers build in. I could easily give away some OSL flags for new keys (CapsLock). I understand that this is nothing to implement easily, but I hope that it is a inspiring suggestion.

**Comment by algernon** [comment]
Compiler flags aren't that great - you can't easily set custom ones in the Arduino IDE, and setting a define in your sketch will have zero effect on how a plugin is compiled - they are separate compilation units. So I'd rather avoid them, if possible.

Nevertheless, the layer<->key tradeoff might be worth exploring. I don't think I'll have time to do that anytime soon, but if someone wants to have a go at it, I'm happy to answer questions and offer what guideance I can.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#419.
