### ISSUE TITLE
Multiple modifiers with one OSM key?

### ISSUE THREAD

**Issue by fredcallaway** [keyboardio/Kaleidoscope-OneShot#33]
I'm not sure if this is possible currently. I would like to be able to tap the butterfly key and then `k`, resulting in a `Ctrl+Alt+k` chord. Is this possible with this plugin? The naive approach `OSM(LCTRL(Key_LeftAlt))` did not work.

**Comment by algernon** [comment]
It's possible, but sadly it is not as easy as `OSM(LCTRL(Key_LeftAlt))` - for the simple reason that we do not have enough bits to represent such a key on the keymap. You can use a macro however, which will trigger a one-shot control and a one-shot alt, one after each other:

```c++
void macroOneShotAltControl(uint8_t keyState) {
  OneShot.inject(OSM(LeftAlt), keyState);
  OneShot.inject(OSM(LeftControl), keyState);
}
```

Mind you, the above is untested, but should work. Please let me know if it does! I'll add it to the README and the example if it works =)

**Comment by fredcallaway** [comment]
Works like a charm! Thanks :)

**Comment by joeynguyen** [comment]
@algernon is there a way to implement the same functionality as above but make all of the modifiers "sticky" on second press of the key?

**Comment by algernon** [comment]
That would be a bit trickier to accomplish...

Something like this, perhaps:

```c++
void macroOneShotAltControl(uint8_t keyState) {
  if (keyIsPressed(keyState) || !OneShot.isActive()) {
    OneShot.inject(OSM(LeftAlt), keyState);
    OneShot.inject(OSM(LeftControl), keyState);
    return;
  }

  if (OneShot.isActive() && keyIsPressed(keyState)) {
    OneShot.cancel();
    OneShot.inject(OSM(LeftAlt), keyState);
    OneShot.inject(OSM(LeftAlt), keyState);
    OneShot.inject(OSM(LeftControl), keyState);
    OneShot.inject(OSM(LeftControl), keyState);
  }
}
```

Mind you, this will clear all other oneshot effects. It may make sense to implement a `OneShot.setSticky()` function to help accomplishing this, so if the above doesn't work, please open another issue requesting the feature. Thanks!

**Comment by joeynguyen** [comment]
Thanks for the code suggestion @algernon.  Unfortunately it didn't work for my exact wants, but it did help put me on a path to figure it out for myself.  I created a new issue where I went into more detail here - https://github.com/keyboardio/Kaleidoscope-OneShot/issues/41
