### ISSUE TITLE
OneShot fails after having been in Sticky state

### ISSUE THREAD

**Issue by hgersen** [keyboardio/Kaleidoscope-OneShot#34]
In trying out oneshot on a new keyboard layout I noticed that I was making a lot of strange mistakes. And it seems like something is not working as expected when I try to use oneshot after I have just used it in sticky mode. To reproduce, try to type:

HHHHHHhhhhhhHHHHHH 

using a double tap on shift in both cases. If I do that I instead get 

HHHHHHHhhhhhhHhhhhh

The problem is that in this case the first hit of the second double tap immediately deactivates, which shouldn't happen.

**Comment by obra** [comment]
There's a chance that this is a hardware issue rather than a software one.
Does it work the same with both shift keys?

Best,
Jesse

**Comment by hgersen** [comment]
I only have a single shift key under one of my thumbs in my layout. Seeing how reproducible and predictable this behavior is I would be very surprised if it would be a hardware issue.

However I've quickly checked by putting shift on another key on the other hand, which shows exactly the same behavior. So I'm pretty convinced it is a software issue.

**Comment by obra** [comment]
Awesome. That's super-useful and helping debugging information.

Best,
Jesse

**Comment by algernon** [comment]
Reproduced, thanks for the report! I was hoping this'll be the same as keyboardio/Kaleidoscope#329, but alas, this is a different issue.

I also found that trying to enter sticky mode for the third time will work correctly, so we're likely not clearing a bit we should be clearing.

**Comment by algernon** [comment]
As it turns out, the fix was trivial, once I managed to figure out the flow, and discover where it went wrong.

Thank you for the report, and apologies for taking this long to fix the issue!
