### ISSUE TITLE
Very short keypress does not trigger OneShot

### ISSUE THREAD

**Issue by Phlogistique** [keyboardio/Kaleidoscope-OneShot#36]
I experience an issue where a very short keypress does not trigger OneShot behaviour, even though the keyboard seems to detect the keypress. A very slightly longer keypress does trigger OneShot.

I know that the keyboard detects the keypress because:

- LED-ActiveModColor makes the LED flash briefly
- When using the keylogger, it does log the keypress (and no other):
```
KL: row=0, col=8, pressed=1, defaultLayer=0, layerState=1, mapped_key.flags=11000000, mapped_key.keyCode=5, timestamp=42537
KL: row=0, col=8, pressed=0, defaultLayer=0, layerState=1, mapped_key.flags=11000000, mapped_key.keyCode=5, timestamp=42549
```

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#418.
