### ISSUE TITLE
 Using double OSM via macro makes them sticky 

### ISSUE THREAD

**Issue by jamadagni** [keyboardio/Kaleidoscope-OneShot#38]
Hello. Based on the [OneShot.inject example](https://github.com/keyboardio/Kaleidoscope-OneShot/blob/701e79d3dc136050a629d83328101e7698c591c6/examples/OneShot/OneShot.ino#L68) I have the following code in my sketch:

```
    case MACRO_OSM_LEVEL4:
        if (keyToggledOn(keyState))
        {
            OneShot.inject(OSM(RightAlt), keyState);
            OneShot.inject(OSM(LeftShift), keyState);
        }
        break;
```

On my Kubuntu system _RightAlt + Shift_ selects the fourth shift level of my a key in the active XKB keyboard layout. So I have made a level 4 key that activates them together.

However triggering this macro once causes the two modifiers to go into sticky mode which is not what is desired. Tapping the level 3 and shift modifiers in sequence doesn't go into sticky mode. 

It is desirable that my virtual Level4 key works like any other OSM key: single tap for one time behaviour and double tap for sticky with third tap for release, but I'm not sure if this is possible within the current framework…

Please look into this.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#420.
