### ISSUE TITLE
Sticky OSL not cancelled by .cancel(true) if last tapped key was no modifier

### ISSUE THREAD

**Issue by cerise21** [keyboardio/Kaleidoscope-OneShot#40]
cf. [forum thread](https://community.keyboard.io/t/how-to-clear-sticky-oneshot-modifiers-and-layers/1703/5)

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#413.
