### ISSUE TITLE
Feature request: Add support for triggering multiple modifier OneShot

### ISSUE THREAD

**Issue by joeynguyen** [keyboardio/Kaleidoscope-OneShot#41]
I brought this up in https://github.com/keyboardio/Kaleidoscope-OneShot/issues/33#issuecomment-401581102.

While the suggested code didn't work for me, it did give me some insight on how to possibly implement it.  I browsed through the docs, codebase and forums, and figured out a way to make it work although I consider what I did a bit hacky.

```
void oneShotCommandAltMacro(uint8_t keyState) {
  /* disable OneShot sticky keys */
  if (
    keyToggledOn(keyState) &&
    OneShot.isActive() &&
    OneShot.isSticky(OSM(RightAlt)) &&
    OneShot.isSticky(OSM(LeftGui))
  ) {
    OneShot.inject(OSM(LeftGui), IS_PRESSED);
    OneShot.inject(OSM(LeftGui), WAS_PRESSED);

    OneShot.inject(OSM(RightAlt), IS_PRESSED);
    OneShot.inject(OSM(RightAlt), WAS_PRESSED);

    return;
  }

  /* enable OneShot sticky keys */
  if (OneShot.isActive() && keyToggledOn(keyState)) {
    OneShot.inject(OSM(LeftGui), IS_PRESSED);
    OneShot.inject(OSM(LeftGui), WAS_PRESSED);
    OneShot.inject(OSM(LeftGui), IS_PRESSED);
    OneShot.inject(OSM(LeftGui), WAS_PRESSED);

    OneShot.inject(OSM(RightAlt), IS_PRESSED);
    OneShot.inject(OSM(RightAlt), WAS_PRESSED);
    OneShot.inject(OSM(RightAlt), IS_PRESSED);
    OneShot.inject(OSM(RightAlt), WAS_PRESSED);

    return;
  }

  /* enable OneShot keys */
  OneShot.inject(OSM(LeftGui), keyState);
  OneShot.inject(OSM(RightAlt), keyState);
}
```
My full .ino file - https://github.com/joeynguyen/dotfiles/blob/1dd3c3827a05172f901b83f0423649529ac315bb/Model01-Firmware/Model01-Firmware.ino

It works but requires checking the "stickiness" of each key I'm trying to use.  I'm sure there's a better way to do this that I wasn't able to figure out due to limited knowledge about the Keyboardio firmware and the C language.  Having first class support with some like `OneShot.setSticky()` that @algernon suggested would probably be cleaner and easier for others to implement for themselves.

However, if you think that code is above is sufficient, I think it may be good to document it for others interested doing something similar for their keyboards.

**Comment by joeynguyen** [comment]
I tried using `OneShot.cancel(true)` for turning off the sticky keys but that didn't work, which I think may have been related to https://github.com/keyboardio/Kaleidoscope-OneShot/issues/40

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#414.
