### ISSUE TITLE
`.double_tap_sticky` should be renamed `.double_tap_sticky_mods`

### ISSUE THREAD

**Issue by jamadagni** [keyboardio/Kaleidoscope-OneShot#42]
The name and description of the other property `.double_tap_sticky_layers` indicates clearly that it applies only to `OSL` keys, but neither the name nor description of this property `.double_tap_sticky` indicates that it applies only to `OSM` keys which is in fact the truth and correct behaviour. 

Thus the property name `.double_tap_sticky` should be deprecated and the clear name `.double_tap_sticky_mods` parallel to `.double_tap_sticky_layers` should be used instead.

**Comment by algernon** [comment]
It's a bit more complicated than that, unfortunately. In the past, we only had `.double_tap_sticky`, and that applied to both modifiers and layers. But there was demand for disabling this for layers only, while still allowing modifiers to double-tap into stickyness, and that's how `.double_tap_sticky_layers` was born. For compatibility reasons, we kept the old name.

You are correct though, that we should eventually transition to the new one, but doing that while retaining compatibility is non-trivial.

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#417.
