### ISSUE TITLE
Holding down key and one shot layer only sends single key press

### ISSUE THREAD

**Issue by harrdb12** [keyboardio/Kaleidoscope-OneShot#43]
### Expected behavior
Holding down <kbd>fn</kbd>+<kbd>h</kbd> should send repeated left key presses. 
### Actual behavior
If it is a One Shot Layer, only one key press ever gets sent, regardless of whether I hold down <kbd>fn</kbd> or sticky it. 
### Extra info
I'm using a fairly vanilla setup... only thing that's different is my keymap is Colemak and I have the Kaleidoscope-LED-ActiveModColor plugin.

**Comment by algernon** [comment]
This is the same as #39.
