### ISSUE TITLE
Possible bug: OneShot.cancel() doesn't clear the Command key (OSM(LeftGui)) on Macs

### ISSUE THREAD

**Issue by joeynguyen** [keyboardio/Kaleidoscope-OneShot#44]
On Model01 **1.23** firmware

I noticed that `OneShot.cancel()` doesn't clear the Command key (OSM(LeftGui)) on Macs. With my implementation, anytime I click any modifier key and then my new multi-modifier OneShot key, it clears out the previous modifiers and applies my new modifiers as "active". However, the exception is the Command key. It stays on and gets another "injection" of the Command key applied, causing it to be "sticky" while my Alt/Option key only becomes "active".

Let me know if that doesn't make sense and I'll try to re-explain.

```
void oneShotCommandAltMacro(uint8_t keyState) {
  /* disable OneShot sticky keys */
  if (
    keyToggledOn(keyState) &&
    OneShot.isActive() &&
    OneShot.isSticky(OSM(RightAlt)) &&
    OneShot.isSticky(OSM(LeftGui))
  ) {
    OneShot.cancel(true);

    return;
  }

  /* enable OneShot sticky keys */
  if (
    keyToggledOn(keyState) &&
    OneShot.isActive() &&
    OneShot.isModifierActive(Key_RightAlt) &&
    OneShot.isModifierActive(Key_LeftGui)
  ) {
    OneShot.cancel();

    OneShot.inject(OSM(LeftGui), keyState);
    OneShot.inject(OSM(LeftGui), keyState);

    OneShot.inject(OSM(RightAlt), keyState);
    OneShot.inject(OSM(RightAlt), keyState);

    return;
  }

  /* cancel other OneShot keys and enable these */
  if (
    keyToggledOn(keyState) &&
    OneShot.isActive()
  ) {
    OneShot.cancel();

    OneShot.inject(OSM(LeftGui), keyState);
    OneShot.inject(OSM(RightAlt), keyState);

    return;
  }

  /* enable OneShot keys */
  if (keyToggledOn(keyState) || !OneShot.isActive()) {
    OneShot.inject(OSM(LeftGui), keyState);
    OneShot.inject(OSM(RightAlt), keyState);
  }
}
```

This is happening with the implementation of my sketch at this commit - https://github.com/joeynguyen/dotfiles/commit/610008f302f0dc286dec86a0c40c5fa87b7557df

**Comment by algernon** [comment]
Apologies for only replying now, I've been caught up in other things.

It looks like `cancel()` in general is misbehaving often, there are multiple reports concerning its behaviour. I'll look into it this coming Friday.

**Comment by joeynguyen** [comment]
No worries!  We're all busy people and I understand contributing to open source takes up a lot of time.  I've managed to get around the issue for my own use case so no rush :)

**Comment by algernon** [comment]
Due to the plugin being merged into the [Kaleidoscope](https://github.com/keyboardio/Kaleidoscope) monorepo, issues are being migrated over there. This issue is going to be tracked further as keyboardio/Kaleidoscope#416.
